apiVersion: v1
kind: PersistentVolume
metadata:
  name: truecommand-pv
  labels:
    name: truecommand # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: truenas-2 # ip addres of nfs server
    path: "/mnt/truenas-2/truecommand" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truecommand-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 4Gi
