---
apiVersion: v1
kind: Service
metadata:
  name: truecommand
spec:
  selector:
    app: truecommand
  ports:
    - port: 80
      name: http-tcmd
      protocol: TCP
      targetPort: http-tcmd
    - port: 443
      name: https-tcmd
      protocol: TCP
      targetPort: https-tcmd
